local default_config = {
  domain = "https://leetcode.com",
  graphql_endpoint = "https://leetcode.com/graphql",
  directory = "/home/dhanus/.leetcode",
  leetcode_session = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiMTQ5OTUzMyIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImRqYW5nby5jb250cmliLmF1dGguYmFja2VuZHMuTW9kZWxCYWNrZW5kIiwiX2F1dGhfdXNlcl9oYXNoIjoiNjJjYWVlZDE5OWZmMGJiZTY4ODZhZDI2ZWJlY2VhNjdjYzIyMDY1OSIsImlkIjoxNDk5NTMzLCJlbWFpbCI6ImRoYW51czMxMzNAZ21haWwuY29tIiwidXNlcm5hbWUiOiJEaGFudXMwMDciLCJ1c2VyX3NsdWciOiJEaGFudXMwMDciLCJhdmF0YXIiOiJodHRwczovL2Fzc2V0cy5sZWV0Y29kZS5jb20vdXNlcnMvYXZhdGFycy9hdmF0YXJfMTY2NzczOTA2MC5wbmciLCJyZWZyZXNoZWRfYXQiOjE2ODExMjQ2ODQsImlwIjoiMTgyLjE5LjM1LjE3NyIsImlkZW50aXR5IjoiYWIwOGVkZjJlNWY4OTZjYTMwZjU0MTUzMDA4YjlkMjkiLCJzZXNzaW9uX2lkIjozNjU4NTAzNCwiX3Nlc3Npb25fZXhwaXJ5IjoxMjA5NjAwfQ.e8sm7VMygexQ2pWupKtANpzSE4jxA6EE1ioxxR1YoAg",
  csrf_token = "SmdVyu2eWFzwCXhZZS3fOnSck5KZQCyNvFAnS3hHyDY5UtrR4UFGVJzjILofaOwr",
  language = "go",
}

return default_config
