local default_config = {
  graphql_endpoint = "https://leetcode.com/graphql",
  directory = "/home/dhanus/.leetcode",
  leetcode_session = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiMTQ5OTUzMyIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImRqYW5nby5jb250cmliLmF1dGguYmFja2VuZHMuTW9kZWxCYWNrZW5kIiwiX2F1dGhfdXNlcl9oYXNoIjoiNjJjYWVlZDE5OWZmMGJiZTY4ODZhZDI2ZWJlY2VhNjdjYzIyMDY1OSIsImlkIjoxNDk5NTMzLCJlbWFpbCI6ImRoYW51czMxMzNAZ21haWwuY29tIiwidXNlcm5hbWUiOiJEaGFudXMwMDciLCJ1c2VyX3NsdWciOiJEaGFudXMwMDciLCJhdmF0YXIiOiJodHRwczovL2Fzc2V0cy5sZWV0Y29kZS5jb20vdXNlcnMvYXZhdGFycy9hdmF0YXJfMTY2NzczOTA2MC5wbmciLCJyZWZyZXNoZWRfYXQiOjE2Nzk0MDA1MTcsImlwIjoiNDkuMjA0LjExNy4yMzEiLCJpZGVudGl0eSI6ImFiMDhlZGYyZTVmODk2Y2EzMGY1NDE1MzAwOGI5ZDI5Iiwic2Vzc2lvbl9pZCI6MzY1ODUwMzQsIl9zZXNzaW9uX2V4cGlyeSI6MTIwOTYwMH0.xiMHbMrmtL2OappIUGMapeSjBtgrsLJjzuZI5W6w3Rs",
  csrf_token = "SmdVyu2eWFzwCXhZZS3fOnSck5KZQCyNvFAnS3hHyDY5UtrR4UFGVJzjILofaOwr",
  language = "go",
}

return default_config
